Upgrade to Native Build Tools 0.9.7.1
spring-projects-experimental/spring-native pull request #1206
Opened 2021-11-02 12:33 UTC by sbrannen

This commit upgrades the spring-aot-gradle-plugin and all Maven based
sample apps to Native Build Tools (NBT) 0.9.7.1

NBT 0.9.6 requires JUnit Platform 1.8 (JUnit 5.8) due to its dependency
on the UniqueIdTrackingListener in the junit-platform-launcher
artifact. The Maven sample apps are currently based on Spring Boot 2.6
RC1 which uses JUnit 5.8.1 (JUnit Platform 1.8.1). Thus, there is no
conflict between the JUnit version used in the sample apps and the
version used by NBT.

However, there is an issue regarding Maven Surefire.

Maven Surefire 3.0.0-M4 introduced support for automatically aligning
the JUnit Platform version used by Surefire with the version needed by
the user's configured version of JUnit Jupiter. Since we are not using
Surefire 3.0 milestones, the parent POM for the Maven sample apps has
to explicitly declare a dependency on the correct version of the
junit-platform-launcher in order to make the UniqueIdTrackingListener
available for Native Build Tools 0.9.6 and higher. The actual version
of the junit-platform-launcher is managed by the junit-bom that is
imported by the spring-boot-starter-parent.

Closes gh-1202

2021-11-02 17:36 UTC, sdeleuze commented
@sbrannen Could you please also update the documentation accordingly (version, Maven configuration)?

2021-11-02 17:37 UTC, sdeleuze requested changes
Could you please also update the documentation accordingly (version, Maven configuration)?

2021-11-02 21:02 UTC, merged

2021-11-02 21:02 UTC, sdeleuze commented
I will do the polish myself in order to be able to run a CI full build tonight.

2021-11-03 09:00 UTC, sbrannen commented
> I will do the polish myself in order to be able to run a CI full build tonight.

2021-11-03 09:06 UTC, sbrannen commented
> Could you please also update the documentation accordingly (version, Maven configuration)?

Regarding the Maven configuration, I think we should probably add a note to the user documentation similar to the following comment:

https://github.com/spring-projects-experimental/spring-native/blob/41591f840429267722fcc0f78bc6ad9648480b7a/samples/maven-parent/pom.xml#L183-L193

Otherwise, Spring Boot users will be confused when the Native Build Tools Maven plugin fails to find the "unique ID files" that should be generated by the `UniqueIdTrackingListener`.

@sdeleuze, what do you think?

2021-11-05 07:16 UTC, sdeleuze commented
@sbrannen Good point indeed, could you please update https://github.com/spring-projects-experimental/spring-native/blob/main/spring-native-docs/src/main/asciidoc/getting-started-native-build-tools.adoc accordingly?